Repository ctx400/sscan, pull requests merged in 2025-02, with the labels that each got.

#24 Feature/unsafe
  Cargo.lock
  Cargo.toml
  OPEN_SOURCE_LICENSES.html
  src/actors/lua_vm.rs
  src/actors/lua_vm/messages.rs
  src/actors/queue/data_item.rs
  src/actors/queue/messages.rs
  src/bin/sscan/cli.rs
  src/bin/sscan/main.rs
  tests/register_api.rs
  tests/register_user_engines.rs
Labels: enhancement

#26 Fix/queueapi
  Cargo.lock
  Cargo.toml
  OPEN_SOURCE_LICENSES.html
  src/userscript_api/queue_api.rs
Labels: bug

#31 Target/v0.12
  Cargo.lock
  Cargo.toml
  OPEN_SOURCE_LICENSES.html
  README.md
  src/actors/lua_vm.rs
  src/actors/lua_vm/messages.rs
  src/actors/queue/messages.rs
  src/bin/sscan/cli.rs
  src/bin/sscan/main.rs
  src/bin/sscan/repl.rs
  src/lib.rs
  src/userscript_api.rs
  src/userscript_api/about_api.rs
  src/userscript_api/help_system.rs
  src/userscript_api/help_system/topics/__generic.txt
  src/userscript_api/help_system/topics/about.txt
  src/userscript_api/help_system/topics/queue.txt
  src/userscript_api/help_system/topics/user_engines.txt
  src/userscript_api/queue_api.rs
  tests/register_api.rs
Labels: documentation, enhancement

#32 Feature/actor/userengine
  src/actors/lua_vm.rs
  src/actors/queue.rs
  src/actors/user_engine.rs
  src/actors/user_engine/error.rs
  src/actors/user_engine/messages.rs
  src/lib.rs
  src/userscript_api.rs
  src/userscript_api/user_engine.rs
  src/userscript_api/user_engine_api.rs
  tests/register_user_engines.rs
Labels: enhancement

#33 Feature/actor/scanmgr
  Cargo.lock
  Cargo.toml
  OPEN_SOURCE_LICENSES.html
  src/actors.rs
  src/actors/lua_vm.rs
  src/actors/lua_vm/messages.rs
  src/actors/scanmgr.rs
  src/actors/scanmgr/error.rs
  src/actors/scanmgr/messages.rs
  src/actors/scanmgr/reply.rs
  src/lib.rs
  src/userscript_api.rs
  src/userscript_api/help_system.rs
  src/userscript_api/help_system/topics/scanmgr.txt
  src/userscript_api/scanmgr_api.rs
Labels: enhancement

#35 Fix/race
  Cargo.lock
  Cargo.toml
  OPEN_SOURCE_LICENSES.html
  src/actors.rs
  src/actors/lua_vm/messages.rs
  src/actors/queue.rs
  src/actors/scanmgr.rs
  src/actors/user_engine.rs
  src/bin/sscan/main.rs
  src/macros.rs
Labels: bug

#55 Fix/v0.15.1
  Cargo.lock
  Cargo.toml
  OPEN_SOURCE_LICENSES.html
  src/userscript_api/fs_api/path_obj.rs
Labels: bug, vc
